export const dummy = [
  { id: "A1" },
  { id: "A2" },
  { id: "A3" },
  { id: "A4" },
  { id: "A5" },
  { id: "A6" },
  { id: "A7" },
  { id: "B1" },
  { id: "B2" },
  { id: "B3" },
  { id: "B4" },
  { id: "B5" },
  { id: "B6" },
  { id: "B7" },
  { id: "C1" },
  { id: "C2" },
  { id: "C3" },
  { id: "C4" },
  { id: "C5" },
  { id: "C6" },
  { id: "C7" },
  { id: "D1" },
  { id: "D2" },
  { id: "D3" },
  { id: "D4" },
  { id: "D5" },
  { id: "D6" },
  { id: "D7" },
  { id: "E1" },
  { id: "E2" },
  { id: "E3" },
  { id: "E4" },
  { id: "E5" },
  { id: "E6" },
  { id: "E7" },
  { id: "F1" },
  { id: "F2" },
  { id: "F3" },
  { id: "F4" },
  { id: "F5" },
  { id: "F6" },
  { id: "F7" },
  { id: "G1" },
  { id: "G2" },
  { id: "G3" },
  { id: "G4" },
  { id: "G5" },
  { id: "G6" },
  { id: "G7" },
];

export const dummy1 = [
  { id: "A8" },
  { id: "A9" },
  { id: "A10" },
  { id: "A11" },
  { id: "A12" },
  { id: "A13" },
  { id: "A14" },
  { id: "B8" },
  { id: "B9" },
  { id: "B10" },
  { id: "B11" },
  { id: "B12" },
  { id: "B13" },
  { id: "B14" },
  { id: "C8" },
  { id: "C9" },
  { id: "C10" },
  { id: "C11" },
  { id: "C12" },
  { id: "C13" },
  { id: "C14" },
  { id: "D8" },
  { id: "D9" },
  { id: "D10" },
  { id: "D11" },
  { id: "D12" },
  { id: "D13" },
  { id: "D14" },
  { id: "E8" },
  { id: "E9" },
  { id: "E10" },
  { id: "E11" },
  { id: "E12" },
  { id: "E13" },
  { id: "E14" },
  { id: "F8" },
  { id: "F9" },
  { id: "F10" },
  { id: "F11" },
  { id: "F12" },
  { id: "F13" },
  { id: "F14" },
  { id: "G8" },
  { id: "G9" },
  { id: "G10" },
  { id: "G11" },
  { id: "G12" },
  { id: "G13" },
  { id: "G14" },
];

export const month = [
  {name: "January"},
  {name: "February"},
  {name: "Maret"},
  {name: "April"},
  {name: "May"},
  {name: "June"},
  {name: "July"},
  {name: "August"},
  {name: "September"},
  {name: "December"},
]